apiVersion: v1 
kind: Pod 
metadata:
  name: pod-multicontainer1
spec:
   containers:
   - name: mynginx-container
     image: nginx:1.15.8
     ports: 
     - containerPort: 80 
   - name: mybusybox-sidecar
     image: busybox
     command: ['sh','-c','while true; do sleep 30; done;'] 
