 apiVersion: v1
 kind: Pod
 metadata:
   name: pod2-configmap
 spec:
   containers:
   - name: busybox
     image: busybox
     command: ['sh', '-c', "echo $(ENV_VAR) && sleep 3600"]
     env:
     - name:  ENV_VAR
       valueFrom:
         configMapKeyRef:
           name: myconfigmap1
           key: key1
