apiVersion: v1 
kind: Pod 
metadata:
  name: my-readyness-probe
spec:
   containers:
   - name: my-nginx-container
     image: nginx
     readinessProbe: 
       httpGet: 
         path: /
         port: 80
       initialDelaySeconds: 5
       periodSeconds: 5 
  
