apiVersion: v1
clusters:
- name: "k8s-ajnouri"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ETXdPREE0TWpFd09Wb1hEVE15TURNd09EQTRNakV3T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTE1MClBJUHNydlAweERJSEIzRmdoWk9oc1JENTNzVWpzcE5sek0rR2d3eVlvVXFQRXNvaXRlNnNMNjZCMHRMelJ1ZmsKVCsyZy9IK3VGSzFNeFNNM3l5b3NWb0J5UDRoU1VRK3NsNkJaRHhsL0hxOU8vTjZlOUMyNkxqUWRnWUh0NDdxOAowRThJVGMwU2hKYnBVL3htdWxwVFAzUFZDczA3OXFTWHBLRnBsSzBsTFVOVWRqbjQ2dmhKb3EwaUo5eVh1TzhRClFqc296S25uVysxbEdQM2xqSUlxbnlSaytza1hrNUxNQnI2QlpwdW1WY1k1MTduVmxMcW83endTU3RLcmhQck4KODFRSVZkZUoxdFZHN1VRdDhtcGFuQ1dLR0pucUE0QTFXOXBSQno1OUpTeTMyaDAvWTBXa1ltT3VNT3orcTFsNQo2ajY0TEdIN21SWk85REZESXY4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQek1MVEdWdHFjZEZubnhtUERhMlpLTTJMT3RNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBYkdzRlhKZ01LbFZPSVhLY1pKZm9jNGNCTGtuNTVlSVh6dy9jc0JjNVBIR295cXFVMwpuMEIzaElXMWFhV0dtUmF2Z2Y1VmJLV0tZVnJBbTkyOGdQTDJjc2FMWEpzL1lmdDYzUjdrWEEybjNQRFRKdlVQCmJJdis0YTJrN3VlT1A3V2hSdTgvTkUrR3d5TE1GUFl1ditCeWk3MFFrbnlSeWZQc2JlSG9wMGM4dzhDd0NRNHgKVnVteUw5Zm9Zam5GSWNMWng3Y1J4aWpuSU9kZk9qdmNPRXdGOFJoSzN5QUY4MnZDMHo0emc4WmJmK0xHcWZmaAovQ3NZVk5hTEMzbmRSbkxJdGFPdURZbUErRXpsNUE5dEh1aytPUEc2dC9OUzd4U3NNRkczV0FaODZCL0hQcHhECmV3TXNQQmlpRHZ5UXNWTEFkM0dNTXRxc3Q4ajNIWTJsVVB6NwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://20fa4de3-7871-4add-a836-9e9fbd6081ae.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@k8s-ajnouri
  context:
    cluster: "k8s-ajnouri"
    user: k8s-ajnouri-admin
current-context: admin@k8s-ajnouri
kind: Config
preferences: {}
users:
- name: k8s-ajnouri-admin
  user:
    token: fxnnLhzeJGAcAEhsmIhrQmdlJ3d5tFchIyLQMmCLbWTHa2liSm66Xlze